import {selectedModel} from '../packages/benchmark/src/selection';
import {build} from "esbuild";
import {execFileSync} from "node:child_process";
import {readFile,writeFile,mkdir,copyFile} from "node:fs/promises";
import path from "node:path";
import {ROOT,json,hash} from "../packages/benchmark/src/artifact";
import {validateManifest} from "../packages/core/src/model";
const selected=await selectedModel();
const directory=selected.directory,manifest=await json(path.join(directory,"manifest.json"));
const packed=await readFile(path.join(directory,"weights.bin"));
validateManifest(manifest,packed.length);
if(hash(packed)!==manifest.sha256 || hash(await readFile(path.join(directory,"manifest.json")))!==selected.manifestSha256) throw new Error("Selected checkpoint hash mismatch");
await writeFile(path.join(ROOT,"packages/core/src/checkpoint.ts"),`// Generated by scripts/build.ts from the selected, unpromoted experiment.\nimport type {ModelManifest} from './model';\nexport const manifest:ModelManifest=${JSON.stringify(manifest)};\nexport const weightsBase64:string=${JSON.stringify(packed.toString("base64"))};\n`);
await mkdir(path.join(ROOT,"packages/core/dist"),{recursive:true});
for(const name of ["index","checkpoint"]) {
  const result=await build({entryPoints:[path.join(ROOT,`packages/core/src/${name}.ts`)],outfile:path.join(ROOT,`packages/core/dist/${name}.js`),bundle:true,format:"esm",platform:"browser",target:"es2022",minify:true,external:["./checkpoint.js"],metafile:true});
  await writeFile(path.join(ROOT,`packages/core/dist/${name}.meta.json`),JSON.stringify(result.metafile));
}
execFileSync(path.join(ROOT,"node_modules/.bin/tsc"),["packages/core/src/index.ts","--declaration","--emitDeclarationOnly","--strict","--skipLibCheck","--module","ESNext","--moduleResolution","bundler","--target","es2022","--lib","es2022,dom","--types","@webgpu/types","--outDir","packages/core/dist"],{cwd:ROOT,stdio:"inherit"});
for(const filename of ["LICENSE","THIRD_PARTY_NOTICES.md"]) await copyFile(path.join(ROOT,filename),path.join(ROOT,"packages/core",filename));
await mkdir(path.join(ROOT,"packages/core/docs"),{recursive:true});
await copyFile(path.join(ROOT,"docs/CONTRACT.md"),path.join(ROOT,"packages/core/docs/CONTRACT.md"));
await mkdir(path.join(ROOT,"apps/website/public/tinysarf"),{recursive:true});
for(const filename of ["index.js","checkpoint.js"]) await copyFile(path.join(ROOT,"packages/core/dist",filename),path.join(ROOT,"apps/website/public/tinysarf",filename));
console.log(`Built ${manifest.id}: ${manifest.reachableWeights} reachable int8 weights (experimental, unpromoted)`);
